version: '3'

services:
  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=replica
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica

  mysql_slave:
    image: mysql:latest
    container_name: mysql_slave
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=replica
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: "mysql_master, mysql_slave" # NOMBRES DE LOS CONTENEDORES
      PMA_ARBITRARY: 1 # ESPECIFICA LOS HOST A LOS QUE
    depends_on:
      - mysql_master
      - mysql_slave
